version: 2.1

commands:
  influxdb-onboarding:
    steps:
      - run:
          name: "Post onBoarding request to InfluxDB 2"
          command: ./scripts/influxdb-onboarding.sh
  prepare:
    description: "Prepare environment to tests"
    steps:
      - checkout
      - influxdb-onboarding
  client-test:
    description: "Run tests"
    parameters:
      python-image:
        type: string
    steps:
      - restore_cache:
          name: Restoring Pip Cache
          keys:
            - &cache-key pip-cache-v8-<< parameters.python-image >>-{{ checksum "requirements.txt" }}-{{ checksum "test-requirements.txt" }}-{{ checksum "extra-requirements.txt" }}
            - pip-cache-v8-<< parameters.python-image >>-
      - run:
          command: |  # use pipenv to install dependencies
            sudo pip install pipenv
            pipenv install
      - run:
          name: "Running tests"
          command: ./scripts/ci-test.sh
      - save_cache:
          name: Saving Pip Cache
          key: *cache-key
          paths:
            - ".venv"
            - "~/.cache/pip"
            # - "/usr/local/lib/python3.8/site-packages"
            # - "/usr/local/lib/python3.7/site-packages"
            # - "/usr/local/lib/python3.6/site-packages"
            - "/usr/local/lib/site-python"
          when: always
jobs:
  tests-python:
    parameters:
      python-image:
        type: string
        default: "circleci/python:3.6-buster"
      influxdb-image:
        type: string
        default: "influxdb:2.0.0-beta"
    docker:
      - image: << parameters.python-image >>
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true
      - image: quay.io/influxdb/<< parameters.influxdb-image >>
    steps:
      - prepare
      - client-test:
          python-image: << parameters.python-image >>
      - store_test_results:
          path: test-reports
      - run:
          name: "Collecting coverage reports"
          command: bash <(curl -s https://codecov.io/bash) -f ./coverage.xml || echo "Codecov did not collect coverage reports"

workflows:
  version: 2
  build:
    jobs:
      - tests-python:
          name: python-3.6
      - tests-python:
          name: python-3.6-nightly
          influxdb-image: "influx:nightly"
      - tests-python:
          name: python-3.7
          python-image: "circleci/python:3.7-buster"
      - tests-python:
          name: python-3.8
          python-image: "circleci/python:3.8-buster"

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - tests-python